[package]
name = "dynasty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstream = "0.6.4"
anstyle = "1.0.4"
anyhow = "1.0.75"
async-compat = "0.2.3"
clap = { version = "4.4.7", features = ["wrap_help", "derive", "string"] }
clap-verbosity-flag = "2.1.0"
dirs = "5.0.1"
duration-str = "0.7.0"
env_logger = "0.10.0"
futures = "0.3.29"
log = "0.4.20"
reqwest = { version = "0.11.22", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.107"
shlex = "1.2.0"
smol = "1.3.0"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.50"
toml = "0.8.4"
url = "2.4.1"
